#!/usr/bin/env osascript
on run
  tell application "Terminal"
    set default settings to settings set "Dracula"
    set current settings of tabs of windows to settings set "Dracula"
  end tell
end run
