#!/usr/bin/env osascript
on run 
  tell application "Terminal"
    set default settings to settings set "Solarized Light"
    set current settings of tabs of windows to settings set "Solarized Light"
  end tell
end run
