#!/usr/bin/env osascript
on run
  tell application "Terminal"
    set default settings to settings set "Material Dark"
    set current settings of tabs of windows to settings set "Material Dark"
  end tell
end run
